@host = http://localhost
@port = 5184
@Restaurants.API_HostAddress = {{host}}:{{port}}

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json
Guid: {{$guid}}
LocalDate: {{$localDatetime iso8601}}
ProjectUrl: {{$projectUrl}}
RandomNumber: {{$randomInt}}
###


GET {{Restaurants.API_HostAddress}}/weatherforecast/first
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json


###


GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Accept: application/json
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json
Content-Type: application/json
{
  "Name": "Spicy Delights",
  "Description": "Spicy Delights",
  "HasDelivery": true,
  "Category": "Fine Dining",
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourment Avenue",
  "PostalCode": "54321"
}
###